### ISSUE TITLE
Checkpoint not found

### ISSUE THREAD

**Issue by abhisheksoni27** [nex3z/tflite-mnist-android#1]
If I train the model locally, and then convert it to *.tflite, it works fine. However, if I use the pre-trained checkpoint, I always get the "Checkpoint not found" error. What's wrong?

**Comment by nex3z** [comment]
I think I've missed a checkpoint file in the folder, please try the attached model. Sorry for that.
[mnist-10000.zip](https://github.com/nex3z/tflite-mnist-android/files/1958383/mnist-10000.zip)

**Comment by abhisheksoni27** [comment]
Thank you! Works like a charm. Cheers. :tada:
