### ISSUE TITLE
请问如何进一步提高准确度？？？

### ISSUE THREAD

**Issue by zfk513** [nex3z/tflite-mnist-android#4]
您好，虽然训练集的准确度看起来很高，但是发现体验并不是很好，像7和9，我的写法基本就没法被正确识别，请问如何进一步提高准确度？？？

**Comment by nex3z** [comment]
可以使用更多训练数据和/或更大的网络。
MNIST 中一些数字的写法可能和实际使用者的写法有一些差异：
![mnist](https://ankivil.com/wp-content/uploads/2016/05/mnist_test_croped-816x461.png)

比如 4 这个数字，MNIST 中的写法为：
![4](https://cs.nyu.edu/~roweis/data/mnist_test4.jpg)
而我通常会写为：
![4](https://user-images.githubusercontent.com/5645004/41532918-7a86a1f2-732b-11e8-8dae-e3d1d47e5ee1.png)
导致我写 4 的识别率很低。

解决这一问题的一个方法，是从实际使用者那里收集更多数据用于训练，让训练数据和测试数据来自相同的分布，使模型能够反映实际使用者的书写习惯。

**Comment by zfk513** [comment]
但是这个工作自己做 emmm 好像有点难 样本量小准确度低 样本量大就很花时间
但是不这么做好像也没其他办法了 ，TFlite 不能训练，可能更好的办法就是模仿mnist的写法 orz

**Comment by nex3z** [comment]
也可以考虑使用 [Artificial Data Synthesis](https://www.youtube.com/watch?v=kvtLGRthW4U) 或 [Data Augmentation](https://www.youtube.com/watch?v=AxC-L46vSmY) 等方法来生成更多的数据。
