### ISSUE TITLE
Grayscale values from ARGB_8888 Bitmap

### ISSUE THREAD

**Issue by abhisheksoni27** [nex3z/tflite-mnist-android#6]
I only get negative values after using your code. (https://stackoverflow.com/questions/52020362/how-to-create-a-bytebuffer-from-bitmap-using-grayscale-pixel-value)

**Comment by nex3z** [comment]
Could you share the image you used?

**Comment by abhisheksoni27** [comment]
Sure.

![device-2018-08-28-125410](https://user-images.githubusercontent.com/4340071/44707528-5b7b8880-aac2-11e8-9057-39e59d946392.png)

![image](https://user-images.githubusercontent.com/4340071/44707547-633b2d00-aac2-11e8-88ec-05ee2539a206.png)


**Note:** I am using FingerPaintView to export the image with the required dimensions.

**Comment by nex3z** [comment]
If you export the image from FingerPaintView and convert it to grayscale, the converted pixel values should be either -1 or -16777216. This is the expected result.

FingerPaintView [draws black stroke](https://github.com/nex3z/FingerPaintView/blob/master/fingerpaintview/src/main/java/com/nex3z/fingerpaintview/FingerPaintView.kt#L126) on [white canvas](https://github.com/nex3z/FingerPaintView/blob/master/fingerpaintview/src/main/java/com/nex3z/fingerpaintview/FingerPaintView.kt#L82). [Black](https://developer.android.com/reference/android/graphics/Color#BLACK) color has the value of -16777216 (0xff000000) and [white](https://developer.android.com/reference/android/graphics/Color#WHITE) color has the value of -1 (0xffffffff). The [convertToGreyScale()](https://github.com/nex3z/tflite-mnist-android/blob/master/android/app/src/main/java/com/nex3z/tflitemnist/Classifier.java#L81) method merely averages over the RGB channel so the result is the same.

I've also [inverted the image](https://github.com/nex3z/tflite-mnist-android/blob/master/android/app/src/main/java/com/nex3z/tflitemnist/MainActivity.java#L49) to match the [training data](http://yann.lecun.com/exdb/mnist/), which has white stroke on black background.

**Comment by abhisheksoni27** [comment]
Thank you for the links! You're right. I am using a similar pipeline as well, where I invert the image first then feed it to the Interpreter. (As seen in the exported image I attached to my last message.)

As you can see in that image, the lines are not smooth and so you expect some of the pixels to not have an exact 1.0f value and lie somewhere in the interval defined by [0, 1]. But that doesn't happen.

**Comment by abhisheksoni27** [comment]
So, as it happens, I am converting a keras `.h5` model directly to `.tflite` and it doesn't work as expected. The probabilities are `< 0.05` for every class. The issue isn't with the code, it's with the conversion process because the same model works in Python as well as JS. Maybe something's wrong with the tflite version on Andriod. Anyway, I am opening an issue in the tensorflow repo!

Thanks for your help.

**Comment by nex3z** [comment]
There may be very few values in (0, 1). 

I used a similar image:

![device-2018-08-29-141204](https://user-images.githubusercontent.com/5645004/44768934-8da9ea80-ab95-11e8-9160-1f1200d794d0.png)

And added log to the method:

```java
private float convertToGreyScale(int color) {
    float ret =  (((color >> 16) & 0xFF) + ((color >> 8) & 0xFF) + (color & 0xFF)) / 3.0f / 255.0f;
    if (ret > 0 && ret < 1) {
        Log.v(LOG_TAG, "convertToGreyScaleByte(): input: " + color + ", output: " + ret);
    }
    return ret;
}
```

There were 4 pixel (out of 784) has value in (0, 1): 

```
convertToGreyScaleByte(): input: -7566196, output: 0.54901963
convertToGreyScaleByte(): input: -15329770, output: 0.08627451
convertToGreyScaleByte(): input: -11447983, output: 0.31764707
convertToGreyScaleByte(): input: -3815995, output: 0.77254903
```

You can try the code above and check the log.
