### ISSUE TITLE
图片shape[?,28,28,1]

### ISSUE THREAD

**Issue by an1018** [nex3z/tflite-mnist-android#7]
@nex3z ，你好，界面写好数字，获取bitmap后，Classifier.java通过convertToGreyScale转为灰度图，
那图片的shape如何从[28,28,1]转为[1,28,28,1]的
麻烦您解释下，谢谢

**Comment by nex3z** [comment]
并没有这一步转换。

[进行预测时](https://github.com/nex3z/tflite-mnist-android/blob/master/android/app/src/main/java/com/nex3z/tflitemnist/Classifier.java#L46)，Interpreter 的 [run 方法](https://github.com/nex3z/tflite-mnist-android/blob/master/android/app/src/main/java/com/nex3z/tflitemnist/Classifier.java#L46)接收一个 [ByteBuffer](https://developer.android.com/reference/java/nio/ByteBuffer) 作为输入，ByteBuffer 是一个一维的结构，需要把图片 flatten 到一维。

[预测方法](https://github.com/nex3z/tflite-mnist-android/blob/master/android/app/src/main/java/com/nex3z/tflitemnist/Classifier.java#L43)接收一个 Bitmap 作为输入，然后通过 convertToGreyScale 转换为灰度并[写入 `mImageData `](https://github.com/nex3z/tflite-mnist-android/blob/master/android/app/src/main/java/com/nex3z/tflitemnist/Classifier.java#L76)。这里 `mImageData` 是一个[容量](https://github.com/nex3z/tflite-mnist-android/blob/master/android/app/src/main/java/com/nex3z/tflitemnist/Classifier.java#L38)为 `4 * BATCH_SIZE * IMG_HEIGHT * IMG_WIDTH * NUM_CHANNEL` 的 `ByteBuffer`。

类似地，如果一次预测的数据有多个样本、多个通道，则也需要按照模型输入维度的顺序，对数据进行 flatten。
