### ISSUE TITLE
Error：Fail to creat classifer.

### ISSUE THREAD

**Issue by redeemme** [nex3z/tflite-mnist-android#8]
I have copy the mnist.tflite generated in Step 1 to /android/app/src/main/assets,but the apk can't work.

**Comment by nex3z** [comment]
Please provide the error message logged form [here](https://github.com/nex3z/tflite-mnist-android/blob/master/android/app/src/main/java/com/nex3z/tflitemnist/MainActivity.java#L65), thanks.

Also don't forget to disable compression in [app/build.gradle](https://github.com/nex3z/tflite-mnist-android/blob/master/android/app/build.gradle#L19)

```
aaptOptions {
    noCompress "tflite"
    noCompress "lite"
}
```

as described [here](https://github.com/nex3z/tflite-mnist-android#step-2-build-android-app).
